/**
 * De iconen die de app gebruikt, op één plek.
 *
 * Alles komt uit Hugeicons (stroke, 1.5px). Door ze hier te hernoemen naar wat
 * ze in déze app betekenen, staat er in de componenten `icons.timer` in plaats
 * van `Timer02Icon`, en kun je een icoon vervangen zonder de rest aan te raken.
 */
import {
  Alert02Icon,
  AiMagicIcon,
  ArrowLeft02Icon,
  ArrowRight02Icon,
  Calendar01Icon,
  Calendar03Icon,
  Camera01Icon,
  Cancel01Icon,
  ChefHatIcon,
  Clock01Icon,
  Copy01Icon,
  Delete02Icon,
  Dish01Icon,
  Idea01Icon,
  Image01Icon,
  InboxIcon,
  LinkSquare02Icon,
  Logout03Icon,
  MinusSignIcon,
  Note02Icon,
  PauseIcon,
  PlayIcon,
  PencilEdit02Icon,
  PlusSignIcon,
  RefreshIcon,
  Search01Icon,
  Settings01Icon,
  Share08Icon,
  ShoppingBasket01Icon,
  StarIcon,
  Tick02Icon,
  ThumbsUpIcon,
  Timer02Icon,
  UserMultiple02Icon,
} from "@hugeicons/core-free-icons";
import type { IconData } from "@/components/Icon";

export const icons = {
  back: ArrowLeft02Icon,
  next: ArrowRight02Icon,
  close: Cancel01Icon,
  camera: Camera01Icon,
  photo: Image01Icon,
  recipes: ChefHatIcon,
  inbox: InboxIcon,
  basket: ShoppingBasket01Icon,
  menu: Calendar03Icon,
  /** Wanneer iets was. Een andere tekening dan `menu`, anders leest een
      datum als een link naar het weekmenu. Zie components/Moment.tsx. */
  date: Calendar01Icon,
  copy: Copy01Icon,
  share: Share08Icon,
  clock: Clock01Icon,
  timer: Timer02Icon,
  play: PlayIcon,
  pause: PauseIcon,
  reset: RefreshIcon,
  done: Tick02Icon,
  delete: Delete02Icon,
  plate: Dish01Icon,
  tip: Idea01Icon,
  source: LinkSquare02Icon,
  logout: Logout03Icon,
  edit: PencilEdit02Icon,
  note: Note02Icon,
  again: ThumbsUpIcon,
  minus: MinusSignIcon,
  plus: PlusSignIcon,
  search: Search01Icon,
  settings: Settings01Icon,
  favorite: StarIcon,
  people: UserMultiple02Icon,
  warning: Alert02Icon,
  ideas: AiMagicIcon,
} satisfies Record<string, IconData>;
